export const localization = {
  signInSignUp: "ورود | ثبت نام",
  cart: "سبد خرید",
  wishlist: "علاقه‌مندی‌ها",
  aboutUs: "درباره ما",
  logOut: "خروج",
  totalPrice: "مجموع مبلغ",
  delete: "حذف",
  cancel: "انصراف",
};

export const pageLocalization = {
  home: {
    shopOurTopCategories: "از بهترین مجموعه‌هایمان خرید کنید",
    allCategories: "همه مجموعه‌ها",
  },
  signIn: {
    signIn: "ورود",
    userName: "نام کاربری",
    password: "رمز عبور",
    forgotPassword: "رمز عبور را فراموش کرده اید؟",
    dontHaveAccount: "حساب کاربری ندارید ؟ ایجاد حساب",
  },
  admin: {
    adminَAccess: "دسترسی‌های مدیر",
    allProducts: "نمایش همه محصولات",
    inventory: "انبار",
    orders: "مدیریت سفارش‌ها",
    welcome: "به پنل ادمین خوش آمدید",
    hi: "سلام",
    productName: "نام کالا",
    division: "دسته بندی",
    actions: "عملیات",
    image: "تصویر",
    productsTable: "جدول محصولات",
    rank: "ردیف",
    price: "قیمت",
    quantity: "موجودی",
    priceQuantityTable: "جدول موجودی و قیمت‌ها",
    addProduct: "افزودن کالا",
    save: "ذخیره",
    ordersTable: "جدول سفارش‌ها",
    fullName: "نام کاربر",
    orderTime: "زمان ثبت سفارش",
    orderCheck: "بررسی سفارش",
    delivered: "ارسال شده",
    notDelivered: "ارسال نشده",
    orderStatus: "وضعیت سفارش",
    category: "مجموعه",
    subcategory: "زیر مجموعه",
    categoriesArray: ["کتاب", "لباس", "کیف", "تکنولوژی", "کفش"],
    book: "کتاب",
    purse: "کیف",
    tech: "تکنولوژی",
    cloth: "لباس",
    shoe: "کفش",
    description: "توضیحات",
    brand: "برند",
    addProductSuccess: "کالا با موفقیت اضافه شد",
    deleteProductSuccess: "کالا با موفقیت حذف شد",
    confirmDeleteProduct: "آیا از حذف کالا مطمئن هستید؟",
  },
};
