export const ROUTES = {
  HOME: "/",
  ABOUT_US: "/about-us",
  CART: "/cart",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  ALL_PRODUCTS: "/all-products",
  CHECKOUT: "/checkout",
  INVENTORY: "/inventory",
  ORDERS: "/orders",
  PRODUCT: "/product",
  PRODUCTS: "/products",
  ADMIN: "/admin",
  PAYMENT: "/payment",
  SUCCESS_PAYMENT: "/success-payment",
  FAIL_PAYMENT: "/fail-payment",
};
